#This is an easier to use and modify makefile, but it is slightly more difficult to read than the simple one:
#
# 'make depend' uses makedepend to automatically generate dependencies 
#               (dependencies are added to end of Makefile)
# 'make'        build executable file 'mycc'
# 'make clean'  removes all .o and executable files
#

# define the C compiler to use
CC = mpicxx

# define any compile-time flags
CFLAGS = -Wall -g -std=c++11

# define any directories containing header files other than /usr/include
#
INCLUDES = -I/u/qqiu/usr/local/mpich-3.1.3/include  -I../include

# define library paths in addition to /usr/lib
#   if I wanted to include libraries not in /usr/lib I'd specify
#   their path using -Lpath, something like:
LFLAGS = -L/u/qqiu/usr/local/mpich-3.1.3/lib  -L../lib

# define any libraries to link into executable:
#   if I want to link in libraries (libx.so or libx.a) I use the -llibname 
#   option, something like (this will link in libmylib.so and libm.so:
LIBS = -lmylib -lm

# define the C source files
SRCS = Point.cpp Messages.cpp CommLayer.cpp MessageBuffer.cpp LocalOctTree.cpp Algorithm.cpp ParallelFMM.cpp 

# define the C object files 
#
# This uses Suffix Replacement within a macro:
#   $(name:string1=string2)
#         For each word in 'name' replace 'string1' with 'string2'
# Below we are replacing the suffix .c of all words in the macro SRCS
# with the .o suffix
#
OBJS = $(SRCS:.cpp=.o)

# define the executable file 
MAIN = ParallelFMM

#
# The following part of the makefile is generic; it can be used to 
# build any executable just by changing the definitions above and by
# deleting dependencies appended to the file from 'make depend'
#

.PHONY: depend clean

all: $(MAIN)
	@echo  ParallelFMM with simple message layer has been compiled

$(MAIN): $(OBJS) 
	$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

# this is a suffix replacement rule for building .o's from .c's
# it uses automatic variables $<: the name of the prerequisite of
# the rule(a .c file) and $@: the name of the target of the rule (a .o file) 
# (see the gnu make manual section about automatic variables)
.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $<  -o $@

clean:
	$(RM) *.o *~ $(MAIN)

depend: $(SRCS)
	makedepend $(INCLUDES) $^

# DO NOT DELETE THIS LINE -- make depend needs it

Point.o: Point.h Common/Options.h /usr/include/stdio.h
Point.o: /usr/include/features.h /usr/include/stdc-predef.h
Point.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
Point.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
Point.o: /usr/include/bits/typesizes.h /usr/include/libio.h
Point.o: /usr/include/_G_config.h /usr/include/wchar.h
Point.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
Messages.o: Messages.h Point.h Common/Options.h /usr/include/stdio.h
Messages.o: /usr/include/features.h /usr/include/stdc-predef.h
Messages.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
Messages.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
Messages.o: /usr/include/bits/typesizes.h /usr/include/libio.h
Messages.o: /usr/include/_G_config.h /usr/include/wchar.h
Messages.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
Messages.o: LocalOctTree.h BaseTree.h Common/Log.h MessageBuffer.h
Messages.o: CommLayer.h /usr/include/assert.h
CommLayer.o: CommLayer.h Messages.h Point.h Common/Options.h
CommLayer.o: /usr/include/stdio.h /usr/include/features.h
CommLayer.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
CommLayer.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
CommLayer.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
CommLayer.o: /usr/include/libio.h /usr/include/_G_config.h
CommLayer.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
CommLayer.o: /usr/include/bits/sys_errlist.h LocalOctTree.h BaseTree.h
CommLayer.o: Common/Log.h MessageBuffer.h /usr/include/assert.h
MessageBuffer.o: MessageBuffer.h CommLayer.h Messages.h Point.h
MessageBuffer.o: Common/Options.h /usr/include/stdio.h
MessageBuffer.o: /usr/include/features.h /usr/include/stdc-predef.h
MessageBuffer.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
MessageBuffer.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
MessageBuffer.o: /usr/include/bits/typesizes.h /usr/include/libio.h
MessageBuffer.o: /usr/include/_G_config.h /usr/include/wchar.h
MessageBuffer.o: /usr/include/bits/stdio_lim.h
MessageBuffer.o: /usr/include/bits/sys_errlist.h LocalOctTree.h BaseTree.h
MessageBuffer.o: Common/Log.h /usr/include/assert.h
LocalOctTree.o: /usr/include/time.h /usr/include/features.h
LocalOctTree.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
LocalOctTree.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
LocalOctTree.o: /usr/include/bits/time.h /usr/include/bits/types.h
LocalOctTree.o: /usr/include/bits/typesizes.h /usr/include/xlocale.h
LocalOctTree.o: LocalOctTree.h BaseTree.h Common/Log.h MessageBuffer.h
LocalOctTree.o: CommLayer.h Messages.h Point.h Common/Options.h
LocalOctTree.o: /usr/include/stdio.h /usr/include/libio.h
LocalOctTree.o: /usr/include/_G_config.h /usr/include/wchar.h
LocalOctTree.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
LocalOctTree.o: /usr/include/assert.h Algorithm.h
Algorithm.o: Algorithm.h LocalOctTree.h BaseTree.h Common/Log.h
Algorithm.o: MessageBuffer.h CommLayer.h Messages.h Point.h Common/Options.h
Algorithm.o: /usr/include/stdio.h /usr/include/features.h
Algorithm.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
Algorithm.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
Algorithm.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
Algorithm.o: /usr/include/libio.h /usr/include/_G_config.h
Algorithm.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
Algorithm.o: /usr/include/bits/sys_errlist.h /usr/include/assert.h
ParallelFMM.o: /usr/include/unistd.h /usr/include/features.h
ParallelFMM.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
ParallelFMM.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
ParallelFMM.o: /usr/include/bits/posix_opt.h /usr/include/bits/environments.h
ParallelFMM.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
ParallelFMM.o: /usr/include/bits/confname.h /usr/include/getopt.h
ParallelFMM.o: Common/Options.h
